apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: anp1
spec:
  priority: 1
  subject:
    namespaces:
      matchLabels:
        kubernetes.io/metadata.name: demo
  ingress:
  - name: "allow-80"
    action: "Allow"
    from:
    - namespaces:
        namespaceSelector: {}
    ports:
      - portNumber:
          protocol: TCP
          port: 80
