apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: anp2
spec:
  priority: 2
  subject:
    namespaces:
      matchLabels:
        kubernetes.io/metadata.name: demo
  ingress:
  - name: "pass-81"
    action: "Pass"
    from:
    - namespaces:
        namespaceSelector: {}
    ports:
      - portNumber:
          protocol: TCP
          port: 81
