apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: anp3
spec:
  priority: 3
  subject:
    namespaces:
      matchLabels:
        kubernetes.io/metadata.name: demo
  ingress:
  - name: "deny-81"
    action: "Deny"
    from:
    - namespaces:
        namespaceSelector: {}
    ports:
      - portNumber:
          protocol: TCP
          port: 81
