apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default
spec:
  subject:
    namespaces:
      matchLabels:
        kubernetes.io/metadata.name: demo
  ingress:
  - name: "baseline-deny"
    action: "Deny"
    from:
    - namespaces:
        namespaceSelector: {}
